df <- read.csv(file = 'household_power_consumption.txt',sep = ";",na.strings = "?")
df$Date <- as.Date(df$Date,format="%d/%m/%Y")
df.subset <- subset(df, Date %in% as.Date(c("2007-02-01","2007-02-02"),format = "%Y-%m-%d"))
df.subset$Time <- as.character(df.subset$Time)
df.subset$DateTime <- paste(df.subset$Date, df.subset$Time, sep = " ")
df.subset$DateTime <- strptime(df.subset$DateTime,format = "%Y-%m-%d %H:%M:%s")

# Plot
par(mfrow = c(2,2), mar = c(4,4,1,1))
with(df.subset, plot(DateTime, Global_active_power, xlab = "", ylab = "Global Active Power", type = "l"))
with(df.subset, plot(DateTime, Voltage, xlab = "", ylab = "Voltage", type = "l"))
with(df.subset, plot(DateTime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering"))
with(df.subset, lines(DateTime, Sub_metering_2, col = "red"))
with(df.subset, lines(DateTime, Sub_metering_3, col = "blue"))
legend(x="topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"), lty = c(1,1,1), cex = 0.7, bty = "n")
with(df.subset, plot(DateTime, Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power"))